sudo: required

services:
  - docker

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - docker build --pull -t raccourci/puppet:debian-9.4 puppet/debian-9.4
  - docker push raccourci/puppet:debian-9.4
  - docker build --pull -t raccourci/puppet:debian-7.11 puppet/debian-7.11
  - docker push raccourci/puppet:debian-7.11
  - docker build --pull -t raccourci/node:9-alpine node/9-alpine/
  - docker push raccourci/node:9-alpine
  - docker build --pull -t raccourci/nginx:alpine nginx/alpine/
  - docker push raccourci/nginx:alpine
  - docker build --pull -t raccourci/php:7-cli-alpine php/7-cli-alpine/
  - docker push raccourci/php:7-cli-alpine
  - docker build --pull -t raccourci/php:7-fpm-alpine php/7-fpm-alpine/
  - docker push raccourci/php:7-fpm-alpine
  - docker build --pull -t raccourci/composer:7-alpine composer/
  - docker push raccourci/composer:7-alpine
  - docker build --pull -t raccourci/wp-cli:7-alpine wp-cli/
  - docker push raccourci/wp-cli:7-alpine
