sudo: required

services:
  - docker

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t raccourci/composer -f composer/Dockerfile
  - docker tag composer raccourci/composer
  - docker push raccourci/composer
