sudo: required

services:
  - docker

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - docker build --pull -t raccourci/puppet:debian11-bullseye puppet/debian11-bullseye
  - docker push raccourci/puppet:debian11-bullseye
  - docker build --pull -t raccourci/puppet:debian10-buster puppet/debian10-buster
  - docker push raccourci/puppet:debian10-buster
  - docker build --pull -t raccourci/puppet:debian9-stretch puppet/debian9-stretch
  - docker push raccourci/puppet:debian9-stretch
  - docker build --pull -t raccourci/puppet:debian8-jessie puppet/debian8-jessie
  - docker push raccourci/puppet:debian8-jessie
  - docker build --pull -t raccourci/node:9-alpine node/9-alpine/
  - docker push raccourci/node:9-alpine
  - docker build --pull -t raccourci/nginx:alpine nginx/alpine/
  - docker push raccourci/nginx:alpine
  - docker build --pull -t raccourci/php:7-cli-alpine php/7-cli-alpine/
  - docker push raccourci/php:7-cli-alpine
  - docker build --pull -t raccourci/php:7-fpm-alpine php/7-fpm-alpine/
  - docker push raccourci/php:7-fpm-alpine
  - docker build --pull -t raccourci/composer:7-alpine composer/
  - docker push raccourci/composer:7-alpine
  - docker build --pull -t raccourci/wp-cli:7-alpine wp-cli/
  - docker push raccourci/wp-cli:7-alpine
